Corrected breaks when plotting array data
eProsima/plotjuggler-fastdds-plugins pull request #50
Opened 2022-12-04 09:23 UTC by dwbertol

The plugin breaks due to memory leaking when the dds message has arrays. This is related to the utilization of DynamicData_ptr and asynchronous deletion of data.
This is in some way related to the same problem of https://github.com/eProsima/Fast-DDS/issues/2970

Signed-off-by: Douglas Bertol [dwbertol@gmail.com](mailto:dwbertol@gmail.com)

2023-01-04 14:20 UTC, juanlofer-eprosima requested changes
Thank you @dwbertol for contributing to this repository, we greatly value every effort from the community to help us improve.

It turns out we have detected and fixed this issue in parallel at PR #51, but we would prefer to join yours once this review is addressed. If it is not possible for you to apply the requested suggestions, we would be willing to do so. But note that we have no permission as it is, hence another PR would need to be created from a branch other than main at your fork .

Thanks again, and wish you a happy new year!

2023-01-04 14:20 UTC, juanlofer-eprosima commented on plugins/datastreamer_plugin/fastdds/ReaderHandler.cpp
> +    std::lock_guard<std::mutex> lock(mtx_data_available_);
What is the purpose of this mutex? I believe it is not necessary, as the callback is executed with the reader's internal mutex taken.

2023-01-04 14:20 UTC, juanlofer-eprosima commented on plugins/datastreamer_plugin/fastdds/ReaderHandler.hpp
> +    eprosima::fastrtps::types::DynamicData* data_;
Either keep this as a `DynamicData_ptr` (as in #51) or add `eprosima::fastrtps::types::DynamicDataFactory::get_instance()->delete_data(data_)` to `ReaderHandler`'s destructor.

2023-01-04 14:20 UTC, juanlofer-eprosima commented on plugins/datastreamer_plugin/utils/dynamic_types_utils.cpp
> +                data->return_loaned_value(child_data);
I would guess this is a workaround to avoid creating a copy which won't be deleted. Am I right?

2023-01-04 14:20 UTC, juanlofer-eprosima commented on plugins/datastreamer_plugin/utils/dynamic_types_utils.cpp
> +    DEBUG("Getting numeric data of kind " << std::to_string(kind) << " in member " << member);
Could you please apply this also to `get_string_type_from_data`?

2023-01-04 16:40 UTC, dwbertol commented on plugins/datastreamer_plugin/fastdds/ReaderHandler.cpp
> +    std::lock_guard<std::mutex> lock(mtx_data_available_);
Sorry this was a test to verify if the callback was in some way being called from different threads. I'll remove this code in the next commit

2023-01-04 16:41 UTC, dwbertol commented on plugins/datastreamer_plugin/fastdds/ReaderHandler.hpp
> +    eprosima::fastrtps::types::DynamicData* data_;
The code will be inserted in the next commit.

2023-01-04 16:43 UTC, dwbertol commented on plugins/datastreamer_plugin/utils/dynamic_types_utils.cpp
> +                data->return_loaned_value(child_data);
Yes, this is a workaround. Fastdds dynamic data smart pointer is trying to deallocate the same data twice, what breaks the execution. So as a workaround this part does not copy data and does not use smart pointers.

2023-01-04 16:44 UTC, dwbertol commented on plugins/datastreamer_plugin/utils/dynamic_types_utils.cpp
> +    DEBUG("Getting numeric data of kind " << std::to_string(kind) << " in member " << member);
Code will be inserted in the next commit.

2023-01-04 16:53 UTC, dwbertol commented
Hello @juanlofer-eprosima. I have made the changes according to the review.

Happy new year!

2023-01-04 17:05 UTC, dwbertol commented on plugins/datastreamer_plugin/utils/dynamic_types_utils.cpp
> +                data->return_loaned_value(child_data);
If you use the "get_complex_value"  function you need to deallocate the memory at some point. That is a little tricky using recursivity.

2023-01-13 08:39 UTC, jparisu approved these changes
LGTM

2023-01-13 08:44 UTC, juanlofer-eprosima approved these changes
LGTM, good job!

2023-01-13 08:50 UTC, merged